### ISSUE TITLE
Firefox network error

### ISSUE THREAD

**Issue by micnic** [modestmaps/modestmaps-js#75]
While zooming or panning an error appears in Firefox console:

"NetworkError: 404 Not Found - http://modestmaps.com/null"

Not observed in other browsers, this error appears after few seconds and can appear multiple times.

**Comment by micnic** [comment]
Update: affects other browsers too. Fixed in pull-request #77

**Comment by timrobertson100** [comment]
This still happens when you use Chrome visiting http://modestmaps.com/ (or your own site using MM) and zoom in and out repeatedly.  Was pull-request #77 included in the current release?

**Comment by micnic** [comment]
@timrobertson100 , no, the PR #77 is still open, the owner of the repo seems to be inactive.
